name: dart_rest_api
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  functions_framework: ^0.2.0
  shelf: ^0.7.9
  shelf_router: ^0.7.4
  shelf_router_generator: ^0.7.2+4
  mongo_dart: ^0.4.4

dev_dependencies:
  build_runner: ^1.10.2
  build_verify: ^1.1.1
  functions_framework_builder: ^0.2.0
  http: ^0.12.0
  test: ^1.15.0
  test_process: ^1.0.0
